name: NextGenFactions
version: '${version}'
main: crypto.anguita.nextgenfactions.NextGenFactionsPlugin
commands:
  f:
    aliases:
      - "faction"
      - "factions"
      - "ngf"
      - "nextgenfactions"
