package crypto.factions.bloodfactions.commons.api;

public enum APIAction {

    GET_FACTION,
    GET_FACTION_BY_NAME,
    CHECK_IF_FACTION_EXISTS_BY_NAME,
    GET_FACTION_OF_PLAYER,
    GET_FACTION_AT_LOCATION,
    GET_FACTION_AT_CHUNK,
    GET_PLAYERS_OF_FACTION,
    SAVE_PLAYER,
    CREATE_FACTION,
    CHECK_IF_PLAYER_HAS_PERMISSION,
    CHECK_IF_PLAYER_HAS_FACTION,
    GET_PLAYER,
    GET_PLAYER_BY_NAME,
    GET_CLAIMS_OF_FACTION,
    GET_ROLE_OF_PLAYER,
    GET_DEFAULT_ROLE_OF_FACTION,
    GET_ROLES_OF_FACTION,
    GET_NUMBER_OF_CLAIMS,
    GET_FACTIONS_CORE,
    SHOW_FACTION

}
